// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBebz_G7_lUUFhRCcelz2twdaEN0orRPbg',
    appId: '1:644218655755:web:b3aab2abd211a2cf9e230e',
    messagingSenderId: '644218655755',
    projectId: 'tamweeniya-staging',
    authDomain: 'tamweeniya-staging.firebaseapp.com',
    storageBucket: 'tamweeniya-staging.firebasestorage.app',
    measurementId: 'G-TCK5LT4HGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4NeM6b_nZ7vfZclYvnDjq9RMj8WoWkvU',
    appId: '1:644218655755:android:5a18abedcdcd1a029e230e',
    messagingSenderId: '644218655755',
    projectId: 'tamweeniya-staging',
    storageBucket: 'tamweeniya-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhqb_5mTWyEL6AtcGwLf347-FJTi1ruI',
    appId: '1:644218655755:ios:3d555ea0afad4f909e230e',
    messagingSenderId: '644218655755',
    projectId: 'tamweeniya-staging',
    storageBucket: 'tamweeniya-staging.firebasestorage.app',
    iosBundleId: 'com.ht.iq.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJhqb_5mTWyEL6AtcGwLf347-FJTi1ruI',
    appId: '1:644218655755:ios:2998e0fd3fd804b79e230e',
    messagingSenderId: '644218655755',
    projectId: 'tamweeniya-staging',
    storageBucket: 'tamweeniya-staging.firebasestorage.app',
    iosBundleId: 'com.example.zendeskTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBebz_G7_lUUFhRCcelz2twdaEN0orRPbg',
    appId: '1:644218655755:web:b3aab2abd211a2cf9e230e',
    messagingSenderId: '644218655755',
    projectId: 'tamweeniya-staging',
    authDomain: 'tamweeniya-staging.firebaseapp.com',
    storageBucket: 'tamweeniya-staging.firebasestorage.app',
    measurementId: 'G-TCK5LT4HGT',
  );
}
